// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yowaaltadowikyvdbocl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvd2FhbHRhZG93aWt5dmRib2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NjY2OTQsImV4cCI6MjA1ODA0MjY5NH0.dFQvKbsmHi9BGstQ6lKgVvtKmunRiAf5EioBZml4oRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);